version: '3.3'

services:
    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        networks:
            - frontend
    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge